name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore MyWebApp.sln
        working-directory: website
      - name: Build
        run: dotnet build MyWebApp.sln --no-restore
        working-directory: website
      - name: Test
        run: dotnet test MyWebApp.sln --no-build --verbosity normal
        working-directory: website
